void main(List<String> arguments) {
  // num a = 10;
  // num b = 11;
  // num c = 12;
  // num d = 13;
  // num e = 14;
  // print(a);
  // print(b);
  // print(c);
  // print(d);
  // print(e);
  // int a = 14;
  // int b = 6;
  // int c = a - b;
  // int d = a + b;
  // int e = a * b;
  // print(a);
  // print(b);
  // print(c);
  // print(d);
  // print(e);
  // double a = 1.2;
  // double b = 2.2;
  // double c = 3.2;
  // double d = 4.2;
  // double e = 5.2;
  // print(a + b);
  // print(c + d);
  // print(e);
//   String name = 'Diana';
//   String surname = 'Talantbekova';
//   String college = 'IUK';
//   String course = 'second';
//   String country = 'Kyrgyzstan';
//   print(name);
//   print(surname);
//   print(college);
//   print(course);
//   print(country);
  // List spisok = [2, 3.3, 'Dd'];
  // print(spisok);
  // Map a = {'Name': 'Diana', 'Age': 17, 'Direction': 'Flutter'};
  // print(a);
  final name = 'Di';
  print(name);
  const intt = 22;
  print(intt);
  var x = 'Didi';
  x = 'Di';
  x = 'Ss';
  print(x);
  dynamic z = 16;
  z = 14;
  z = 10;
  print(z);
}
